/// Generated by AssetsRefGenerator on 2022/03/09
///
const String image = 'https://cdn.pixabay'
    '.com/photo/2015/04/23/22/00/tree-736885_1280.jpg';

class Res {
  //images
  static const String login_header = 'assets/images/png/login_header.png';

//   svg

  static const String view_eye = 'assets/images/svg/view_eye.svg';
  static const String hide_eye = 'assets/images/svg/hide_eye.svg';
}
