/// Generated by AssetsRefGenerator on 2022/03/09
///
const String image = 'https://cdn.pixabay'
    '.com/photo/2015/04/23/22/00/tree-736885_1280.jpg';

class Res {
  //images

  static const String peopleAnimation =
      "assets/animations/people_animation.json";
  static const String logo = "assets/images/png/logo.png";
  static const String background = "assets/images/png/background.png";
  static const String people = "assets/images/png/people.png";

  //png

  //svg
  static const String link = "assets/images/svg/link.svg";
  // static const String people = "assets/images/svg/people.svg";
}
